AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Vagrantfile'
    - 'vagrant/**'
    - 'vendor/**/*'
    - 'bin/**'
    - 'chef-repo/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'config/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Rakefile'

ClassAndModuleChildren:
  Enabled: false

MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

GuardClause:
  MinBodyLength: 3

CyclomaticComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

inherit_from: .rubocop_todo.yml

