language: ruby
rvm:
  - 2.6.1
bundler_args: --without development
before_script:
  - cp config/core.yml.sample config/core.yml
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup RAILS_ENV=test
script:
  - bundle exec rake spec
notifications:
  email: false
