default: &default
  enabled: false
  command: slonik_execute_script -c $SQL 1 | sed "s/set id = 1,//" | slonik
  owner: joruri

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
