puts "loading sys_users..."
load "db/seeds/sites/0001/db/sys_users.rb"
puts "loading sys_groups..."
load "db/seeds/sites/0001/db/sys_groups.rb"
puts "loading sys_users_groups..."
load "db/seeds/sites/0001/db/sys_users_groups.rb"
puts "loading cms_sites..."
load "db/seeds/sites/0001/db/cms_sites.rb"
puts "loading cms_site_settings..."
load "db/seeds/sites/0001/db/cms_site_settings.rb"
puts "loading cms_site_belongings..."
load "db/seeds/sites/0001/db/cms_site_belongings.rb"
puts "loading cms_concepts..."
load "db/seeds/sites/0001/db/cms_concepts.rb"
puts "loading cms_data_file_nodes..."
load "db/seeds/sites/0001/db/cms_data_file_nodes.rb"
puts "loading cms_data_files..."
load "db/seeds/sites/0001/db/cms_data_files.rb"
puts "loading cms_data_texts..."
load "db/seeds/sites/0001/db/cms_data_texts.rb"
puts "loading cms_layouts..."
load "db/seeds/sites/0001/db/cms_layouts.rb"
puts "loading cms_contents..."
load "db/seeds/sites/0001/db/cms_contents.rb"
puts "loading cms_nodes..."
load "db/seeds/sites/0001/db/cms_nodes.rb"
puts "loading cms_stylesheets..."
load "db/seeds/sites/0001/db/cms_stylesheets.rb"
puts "loading sys_sequences..."
load "db/seeds/sites/0001/db/sys_sequences.rb"
puts "loading gp_category_template_modules..."
load "db/seeds/sites/0001/db/gp_category_template_modules.rb"
puts "loading gp_category_templates..."
load "db/seeds/sites/0001/db/gp_category_templates.rb"
puts "loading gp_category_category_types..."
load "db/seeds/sites/0001/db/gp_category_category_types.rb"
puts "loading gp_category_categories..."
load "db/seeds/sites/0001/db/gp_category_categories.rb"
puts "loading cms_pieces..."
load "db/seeds/sites/0001/db/cms_pieces.rb"
puts "loading ad_banner_groups..."
load "db/seeds/sites/0001/db/ad_banner_groups.rb"
puts "loading ad_banner_banners..."
load "db/seeds/sites/0001/db/ad_banner_banners.rb"
puts "loading approval_approval_flows..."
load "db/seeds/sites/0001/db/approval_approval_flows.rb"
puts "loading approval_approvals..."
load "db/seeds/sites/0001/db/approval_approvals.rb"
puts "loading organization_groups..."
load "db/seeds/sites/0001/db/organization_groups.rb"
puts "loading tag_tags..."
load "db/seeds/sites/0001/db/tag_tags.rb"
puts "loading gnav_menu_items..."
load "db/seeds/sites/0001/db/gnav_menu_items.rb"
puts "loading gnav_category_sets..."
load "db/seeds/sites/0001/db/gnav_category_sets.rb"
puts "loading gp_calendar_events..."
load "db/seeds/sites/0001/db/gp_calendar_events.rb"
puts "loading gp_article_docs..."
load "db/seeds/sites/0001/db/gp_article_docs.rb"
puts "loading gp_article_docs_tag_tags..."
load "db/seeds/sites/0001/db/gp_article_docs_tag_tags.rb"
puts "loading gp_article_related_docs..."
load "db/seeds/sites/0001/db/gp_article_related_docs.rb"
puts "loading survey_forms..."
load "db/seeds/sites/0001/db/survey_forms.rb"
puts "loading survey_questions..."
load "db/seeds/sites/0001/db/survey_questions.rb"
puts "loading cms_content_settings..."
load "db/seeds/sites/0001/db/cms_content_settings.rb"
puts "loading cms_piece_settings..."
load "db/seeds/sites/0001/db/cms_piece_settings.rb"
puts "loading approval_assignments..."
load "db/seeds/sites/0001/db/approval_assignments.rb"
puts "loading gp_category_categorizations..."
load "db/seeds/sites/0001/db/gp_category_categorizations.rb"
puts "loading sys_files..."
load "db/seeds/sites/0001/db/sys_files.rb"
puts "loading sys_creators..."
load "db/seeds/sites/0001/db/sys_creators.rb"
puts "loading sys_editors..."
load "db/seeds/sites/0001/db/sys_editors.rb"
puts "loading cms_brackets..."
load "db/seeds/sites/0001/db/cms_brackets.rb"
puts "loading cms_inquiries..."
load "db/seeds/sites/0001/db/cms_inquiries.rb"
puts "loading cms_links..."
load "db/seeds/sites/0001/db/cms_links.rb"
puts "loading cms_periods..."
load "db/seeds/sites/0001/db/cms_periods.rb"
puts "loading cms_publish_urls..."
load "db/seeds/sites/0001/db/cms_publish_urls.rb"
puts "loading cms_maps..."
load "db/seeds/sites/0001/db/cms_maps.rb"
puts "loading cms_map_markers..."
load "db/seeds/sites/0001/db/cms_map_markers.rb"

# copy files
puts "copying files..."
src = Rails.root.join("db/seeds/sites/0001/public/.")
dst = Rails.root.join("sites/#{format('%04d', @cms_sites_1.id)}/public")
FileUtils.mkdir_p(dst) unless Dir.exist?(dst)
FileUtils.cp_r(src, dst) if Dir.exists?(src)
