AdBanner::Banner.create!([
  {id: 1, name: "topphoto01.jpg", title: "キービジュアル１", mime_type: "image/jpeg", size: 108526, image_is: 1, image_width: 1200, image_height: 360, content_id: 8, group_id: 1, state: "public", advertiser_name: "じょうるり市", advertiser_phone: "", advertiser_email: "", advertiser_contact: "", published_at: nil, closed_at: nil, url: "/", sort_no: 10, token: "PytqxdAr2QMcEGPgqGZM", target: "_self", site_id: 1, thumb_width: 120, thumb_height: 90, thumb_size: 2138, alt_text: "キービジュアル１"},
  {id: 2, name: "topphoto02.jpg", title: "キービジュアル２", mime_type: "image/jpeg", size: 46577, image_is: 1, image_width: 1200, image_height: 360, content_id: 8, group_id: 1, state: "public", advertiser_name: "じょうるり市", advertiser_phone: "", advertiser_email: "", advertiser_contact: "", published_at: nil, closed_at: nil, url: "/", sort_no: 20, token: "cazdM5zWxD2cqbCb1Y7q", target: "_self", site_id: 1, thumb_width: 120, thumb_height: 90, thumb_size: 1941, alt_text: "キービジュアル２"},
  {id: 3, name: "bn-joruri.gif", title: "Joruri公式サイト", mime_type: "image/gif", size: 2126, image_is: 1, image_width: 170, image_height: 50, content_id: 8, group_id: 2, state: "public", advertiser_name: "サイトブリッジ株式会社", advertiser_phone: "", advertiser_email: "", advertiser_contact: "", published_at: nil, closed_at: nil, url: "http://joruri.org/", sort_no: 100, token: "d194WzKixEz4sNjr36sp", target: "_blank", site_id: 1, thumb_width: 120, thumb_height: 90, thumb_size: 2143, alt_text: "Joruri公式サイト"},
  {id: 4, name: "bn-jorurionline.gif", title: "Joruri ONLINE", mime_type: "image/gif", size: 1073, image_is: 1, image_width: 170, image_height: 50, content_id: 8, group_id: 2, state: "public", advertiser_name: "サイトブリッジ株式会社", advertiser_phone: "", advertiser_email: "", advertiser_contact: "", published_at: nil, closed_at: nil, url: "http://joruri-online.jp/", sort_no: 200, token: "yQUyh9q6XHHzhmAVZhnt", target: "_blank", site_id: 1, thumb_width: 120, thumb_height: 90, thumb_size: 1732, alt_text: "Joruri ONLINE"},
  {id: 5, name: "bn-sitebridge.gif", title: "サイトブリッジ株式会社", mime_type: "image/gif", size: 975, image_is: 1, image_width: 170, image_height: 50, content_id: 8, group_id: 2, state: "public", advertiser_name: "サイトブリッジ株式会社", advertiser_phone: "", advertiser_email: "", advertiser_contact: "", published_at: nil, closed_at: nil, url: "http://www.sitebridge.co.jp/", sort_no: 300, token: "shzEsfzLKKF1QE24fnJ1", target: "_blank", site_id: 1, thumb_width: 120, thumb_height: 90, thumb_size: 1479, alt_text: "サイトブリッジ株式会社"}
])
AdBanner::Group.create!([
  {id: 1, content_id: 8, name: "keyvisual", title: "キービジュアル", sort_no: 10},
  {id: 2, content_id: 8, name: "ad-banner-lower", title: "広告バナー（下部）", sort_no: 20},
  {id: 3, content_id: 8, name: "ad-banner-side", title: "広告バナー（サイド）", sort_no: 30}
])
