GpCategory::Category.create!([
  {id: 44, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "juminhyo", title: "住民票", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 45, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "inkan", title: "印鑑登録", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 46, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "koseki", title: "戸籍", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 47, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "gaikokujin", title: "外国人登録", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 48, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "shomei", title: "各種証明書", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 49, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "jukinet", title: "住基ネット・公的個人認証", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 50, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "passport", title: "パスポート", level_no: 2, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 51, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "my-number", title: "マイナンバー制度", level_no: 2, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 52, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 23, state: "public", name: "procedure", title: "手続き・本人確認・委任", level_no: 2, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 53, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 24, state: "public", name: "kokuho", title: "国民健康保険", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 54, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 24, state: "public", name: "nenkin", title: "国民年金", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 55, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 24, state: "public", name: "kaigo", title: "介護保険", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 56, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 24, state: "public", name: "kouki", title: "後期高齢者医療", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 57, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "fuyo", title: "児童扶養手当", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 58, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "hitori", title: "ひとり親家庭助成", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 59, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "tokubetsu", title: "特別児童扶養手当", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 60, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "shogai", title: "障がい者助成", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 61, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "korei", title: "高齢者福祉", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 62, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 25, state: "public", name: "seikatsuhogo", title: "生活保護", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 63, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "boshihoken", title: "母子保健", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 64, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "yobo", title: "予防接種", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 65, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "tokuteikenshin", title: "総合健(検)診･保健指導", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 66, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "kenko", title: "健康づくり", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 67, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "infection", title: "感染症", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 68, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 26, state: "public", name: "sonota", title: "その他", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 69, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "shikenmin", title: "市県民税", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 70, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "shizei_gaiyo", title: "市税概要", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 71, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "koteishisan", title: "固定資産税", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 72, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "keijidosha", title: "軽自動車税", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 73, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "sonota", title: "その他の税", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 74, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "nofu", title: "納付・収納", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 75, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "shomeisho", title: "税務関連証明書", level_no: 2, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 76, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "kobai", title: "公売情報", level_no: 2, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 77, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 27, state: "public", name: "furusato", title: "ふるさと納税", level_no: 2, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 78, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "hoikusho", title: "保育所", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 79, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "yochien", title: "幼稚園", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 80, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "ikujishien", title: "育児支援", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 81, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "gakudohoiku", title: "学童保育", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 82, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "gakko", title: "学校教育", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 83, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "kyushoku", title: "給食", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 84, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "shogaigakushu", title: "生涯学習", level_no: 2, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 85, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "shugakutaiyo", title: "就学資金貸与", level_no: 2, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 86, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 28, state: "public", name: "education", title: "教育委員会", level_no: 2, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 87, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 29, state: "public", name: "koeijutaku", title: "公営住宅", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 88, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 29, state: "public", name: "suido", title: "上水道", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 89, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 29, state: "public", name: "gesuido", title: "下水道", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 90, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 29, state: "public", name: "doro", title: "道路", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 91, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 29, state: "public", name: "kokyo", title: "公共交通（電車・バスなど）", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 92, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 30, state: "public", name: "kyukyu", title: "救急・消防", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 93, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 30, state: "public", name: "kyujitsushinryo", title: "休日診療案内", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 94, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 30, state: "public", name: "bosaigai", title: "防災・災害", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 95, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 30, state: "public", name: "bohan", title: "防犯・交通安全", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 96, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 30, state: "public", name: "jiko", title: "事故・被災支援", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 97, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 31, state: "public", name: "gomi", title: "ごみ・リサイクル", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 98, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 31, state: "public", name: "pet", title: "ペット・動物愛護", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 99, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 31, state: "public", name: "eco", title: "エコ・環境・公害", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 100, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 32, state: "public", name: "joho", title: "入札情報", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 101, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 32, state: "public", name: "kobo", title: "公募", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 102, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 32, state: "public", name: "shikakushinsei", title: "入札参加資格申請", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 103, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 32, state: "public", name: "shokibokoji", title: "小規模工事等業者登録", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 104, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 32, state: "public", name: "henko", title: "入札参加資格申請変更届け", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 105, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 33, state: "public", name: "keikaku", title: "都市計画・まちづくり", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 106, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 33, state: "public", name: "doro", title: "道路整備", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 107, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 34, state: "public", name: "kigyoyushi", title: "企業融資・支援", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 108, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 34, state: "public", name: "noringyo", title: "農業・林業", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 109, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 34, state: "public", name: "shokogyo", title: "商業・工業", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 110, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 34, state: "public", name: "koyo", title: "雇用", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 111, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 35, state: "public", name: "shokai", title: "市紹介", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 114, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 35, state: "public", name: "saiyo", title: "職員採用", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 112, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 35, state: "public", name: "kyodosankaku", title: "男女共同参画", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 118, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 35, state: "public", name: "site", title: "市ホームページ", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 116, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 36, state: "public", name: "kanko", title: "観光", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 117, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 36, state: "public", name: "bussan", title: "物産", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 115, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 36, state: "public", name: "rekishi", title: "歴史・文化財", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 121, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "bunka_sports", title: "文化・スポーツ施設", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 119, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "shiyakusho", title: "市役所", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 120, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "hukushi", title: "福祉・保健施設", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 122, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "hoikusho", title: "保育所", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 123, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "yochien", title: "幼稚園", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 124, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "shochugakko", title: "小学校・中学校", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 125, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "kominkan", title: "公民館", level_no: 2, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 126, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "center", title: "男女共同参画推進センター", level_no: 2, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 127, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "koen", title: "公園", level_no: 2, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 128, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "shieijyutaku", title: "市営住宅", level_no: 2, sort_no: 100, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 129, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "museum", title: "美術館", level_no: 2, sort_no: 110, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 130, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 37, state: "public", name: "bochi", title: "斎場・墓地", level_no: 2, sort_no: 120, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 131, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 39, state: "public", name: "gikai", title: "議会", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 132, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 39, state: "public", name: "senkyo", title: "選挙", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 133, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 40, state: "public", name: "koho", title: "広報", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 134, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 40, state: "public", name: "kocho", title: "広聴", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 135, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 40, state: "public", name: "gyoseisodan", title: "行政相談窓口", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 136, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "johokokai_kojinjoho", title: "情報公開・個人情報制度", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 137, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "keikaku", title: "計画・取り組み", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 138, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "zaisei", title: "財政状況", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 139, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "tokei", title: "統計", level_no: 2, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 140, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "jorei_reiki", title: "条例・例規集\t", level_no: 2, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 141, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 41, state: "public", name: "kyuyoteisu", title: "職員給与・定員管理", level_no: 2, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 142, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 42, state: "public", name: "kokusai", title: "国際交流", level_no: 2, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 143, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 42, state: "public", name: "heiwakoryu", title: "平和交流", level_no: 2, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 144, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: 42, state: "public", name: "yukotoshikoryu", title: "友好都市交流", level_no: 2, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 7, children_count: 0},
  {id: 23, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "todokede", title: "届出・登録・証明", level_no: 1, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 9},
  {id: 24, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "hoken", title: "保険・年金・介護", level_no: 1, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 4},
  {id: 25, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "hukushi", title: "福祉", level_no: 1, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 6},
  {id: 26, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "kenko", title: "健康・予防", level_no: 1, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 6},
  {id: 27, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "zei", title: "税金", level_no: 1, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 9},
  {id: 28, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "ikuji", title: "育児・教育", level_no: 1, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 9},
  {id: 29, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "seikatsu", title: "生活・インフラ", level_no: 1, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 5},
  {id: 30, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "anshin", title: "安心・安全", level_no: 1, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 5},
  {id: 31, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "kankyo", title: "環境・ごみ", level_no: 1, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 3},
  {id: 32, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "nyusatsu", title: "入札・契約", level_no: 1, sort_no: 100, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 5},
  {id: 33, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "toshiseibi", title: "都市整備", level_no: 1, sort_no: 110, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 2},
  {id: 34, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "chiikisangyo", title: "地域産業", level_no: 1, sort_no: 120, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 4},
  {id: 35, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "shisei", title: "市政情報", level_no: 1, sort_no: 130, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 4},
  {id: 36, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "kanko", title: "観光・物産", level_no: 1, sort_no: 140, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 3},
  {id: 37, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "shisetsu", title: "施設案内", level_no: 1, sort_no: 150, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 12},
  {id: 39, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "gikai_senkyo", title: "議会・選挙", level_no: 1, sort_no: 160, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 2},
  {id: 40, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "kohokocho", title: "広報・広聴", level_no: 1, sort_no: 170, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 3},
  {id: 41, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "johokokai", title: "情報公開", level_no: 1, sort_no: 180, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 6},
  {id: 42, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "koryu", title: "交流事業", level_no: 1, sort_no: 190, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 3},
  {id: 43, concept_id: nil, layout_id: nil, category_type_id: 1, parent_id: nil, state: "public", name: "nayami", title: "悩み・相談", level_no: 1, sort_no: 200, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 3, children_count: 0},
  {id: 1, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "chumoku", title: "注目情報", level_no: 1, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 10, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "download", title: "ダウンロード", level_no: 1, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 11, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "tetsuzuki", title: "手続き", level_no: 1, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 12, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "boshu", title: "募集", level_no: 1, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 9, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "opendata", title: "オープンデータ", level_no: 1, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 3, concept_id: nil, layout_id: nil, category_type_id: 2, parent_id: nil, state: "public", name: "emergency", title: "緊急情報", level_no: 1, sort_no: 100, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 5, children_count: 0},
  {id: 13, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "ninshin", title: "妊娠・出産", level_no: 1, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 14, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "kosodate", title: "子育て・教育", level_no: 1, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 15, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "seijin", title: "成人・就職", level_no: 1, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 16, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "kekkon", title: "結婚・離婚", level_no: 1, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 17, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "hikkoshi", title: "引越し・住まい", level_no: 1, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 18, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "byoki", title: "病気・けが", level_no: 1, sort_no: 60, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 19, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "shogaisha", title: "障がい者", level_no: 1, sort_no: 70, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 20, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "shitsugyo", title: "失業・退職", level_no: 1, sort_no: 80, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 21, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "korei", title: "高齢・介護", level_no: 1, sort_no: 90, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 22, concept_id: nil, layout_id: nil, category_type_id: 3, parent_id: nil, state: "public", name: "shibo", title: "死亡・相続", level_no: 1, sort_no: 100, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 4, children_count: 0},
  {id: 4, concept_id: nil, layout_id: nil, category_type_id: 4, parent_id: nil, state: "public", name: "event", title: "イベント", level_no: 1, sort_no: 10, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 6, children_count: 0},
  {id: 5, concept_id: nil, layout_id: nil, category_type_id: 4, parent_id: nil, state: "public", name: "sports", title: "スポーツ", level_no: 1, sort_no: 20, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 6, children_count: 0},
  {id: 6, concept_id: nil, layout_id: nil, category_type_id: 4, parent_id: nil, state: "public", name: "koza", title: "講座", level_no: 1, sort_no: 30, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 6, children_count: 0},
  {id: 7, concept_id: nil, layout_id: nil, category_type_id: 4, parent_id: nil, state: "public", name: "matsuri", title: "お祭り", level_no: 1, sort_no: 40, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 6, children_count: 0},
  {id: 8, concept_id: nil, layout_id: nil, category_type_id: 4, parent_id: nil, state: "public", name: "teireikai", title: "定例会", level_no: 1, sort_no: 50, description: "", group_code: nil, sitemap_state: "visible", docs_order: "", template_id: 6, children_count: 0}
])
GpCategory::Categorization.create!([
  {id: 113, categorizable_id: 54, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 357, categorizable_id: 178, categorizable_type: "GpArticle::Doc", category_id: 100, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 114, categorizable_id: 54, categorizable_type: "GpArticle::Doc", category_id: 50, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 449, categorizable_id: 262, categorizable_type: "GpArticle::Doc", category_id: 63, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 67, categorizable_id: 40, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 68, categorizable_id: 40, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 69, categorizable_id: 40, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 43, categorizable_id: 1, categorizable_type: "GpCalendar::Event", category_id: 4, sort_no: nil, categorized_as: nil},
  {id: 44, categorizable_id: 1, categorizable_type: "GpCalendar::Event", category_id: 5, sort_no: nil, categorized_as: nil},
  {id: 115, categorizable_id: 55, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 116, categorizable_id: 55, categorizable_type: "GpArticle::Doc", category_id: 51, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 117, categorizable_id: 56, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 118, categorizable_id: 56, categorizable_type: "GpArticle::Doc", category_id: 51, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 73, categorizable_id: 42, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 74, categorizable_id: 42, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 75, categorizable_id: 42, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 76, categorizable_id: 43, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 77, categorizable_id: 43, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 78, categorizable_id: 43, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 123, categorizable_id: 59, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 79, categorizable_id: 44, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 80, categorizable_id: 44, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 81, categorizable_id: 44, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 82, categorizable_id: 45, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 83, categorizable_id: 45, categorizable_type: "GpArticle::Doc", category_id: 45, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 122, categorizable_id: 59, categorizable_type: "GpArticle::Doc", category_id: 51, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 84, categorizable_id: 45, categorizable_type: "GpArticle::Doc", category_id: 16, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 53, categorizable_id: 30, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 85, categorizable_id: 45, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 54, categorizable_id: 31, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 124, categorizable_id: 60, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 55, categorizable_id: 32, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 86, categorizable_id: 46, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 56, categorizable_id: 33, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 57, categorizable_id: 34, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 87, categorizable_id: 46, categorizable_type: "GpArticle::Doc", category_id: 45, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 58, categorizable_id: 35, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 125, categorizable_id: 60, categorizable_type: "GpArticle::Doc", category_id: 52, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 59, categorizable_id: 36, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 88, categorizable_id: 46, categorizable_type: "GpArticle::Doc", category_id: 16, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 60, categorizable_id: 37, categorizable_type: "GpArticle::Doc", category_id: 119, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 61, categorizable_id: 37, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 89, categorizable_id: 46, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 126, categorizable_id: 61, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 127, categorizable_id: 61, categorizable_type: "GpArticle::Doc", category_id: 52, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 90, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 128, categorizable_id: 62, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 129, categorizable_id: 62, categorizable_type: "GpArticle::Doc", category_id: 52, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 96, categorizable_id: 48, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 91, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 46, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 92, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 130, categorizable_id: 63, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 93, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 16, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 94, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 131, categorizable_id: 63, categorizable_type: "GpArticle::Doc", category_id: 53, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 95, categorizable_id: 47, categorizable_type: "GpArticle::Doc", category_id: 22, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 97, categorizable_id: 48, categorizable_type: "GpArticle::Doc", category_id: 47, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 132, categorizable_id: 64, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 98, categorizable_id: 48, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 99, categorizable_id: 49, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 133, categorizable_id: 64, categorizable_type: "GpArticle::Doc", category_id: 53, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 100, categorizable_id: 49, categorizable_type: "GpArticle::Doc", category_id: 48, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 101, categorizable_id: 50, categorizable_type: "GpArticle::Doc", category_id: 10, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 134, categorizable_id: 65, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 102, categorizable_id: 50, categorizable_type: "GpArticle::Doc", category_id: 48, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 103, categorizable_id: 50, categorizable_type: "GpArticle::Doc", category_id: 16, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 135, categorizable_id: 65, categorizable_type: "GpArticle::Doc", category_id: 53, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 104, categorizable_id: 50, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 136, categorizable_id: 65, categorizable_type: "GpArticle::Doc", category_id: 20, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 137, categorizable_id: 66, categorizable_type: "GpArticle::Doc", category_id: 54, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 138, categorizable_id: 66, categorizable_type: "GpArticle::Doc", category_id: 15, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 107, categorizable_id: 52, categorizable_type: "GpArticle::Doc", category_id: 49, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 108, categorizable_id: 52, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 109, categorizable_id: 52, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 139, categorizable_id: 66, categorizable_type: "GpArticle::Doc", category_id: 20, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 110, categorizable_id: 53, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 111, categorizable_id: 53, categorizable_type: "GpArticle::Doc", category_id: 49, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 140, categorizable_id: 67, categorizable_type: "GpArticle::Doc", category_id: 54, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 112, categorizable_id: 53, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 141, categorizable_id: 68, categorizable_type: "GpArticle::Doc", category_id: 54, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 142, categorizable_id: 69, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 143, categorizable_id: 69, categorizable_type: "GpArticle::Doc", category_id: 55, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 145, categorizable_id: 70, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 358, categorizable_id: 179, categorizable_type: "GpArticle::Doc", category_id: 100, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 144, categorizable_id: 69, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 263, categorizable_id: 120, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 179, categorizable_id: 82, categorizable_type: "GpArticle::Doc", category_id: 60, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 180, categorizable_id: 82, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 264, categorizable_id: 120, categorizable_type: "GpArticle::Doc", category_id: 75, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 182, categorizable_id: 83, categorizable_type: "GpArticle::Doc", category_id: 60, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 183, categorizable_id: 83, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 184, categorizable_id: 83, categorizable_type: "GpArticle::Doc", category_id: 19, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 265, categorizable_id: 121, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 193, categorizable_id: 87, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 194, categorizable_id: 87, categorizable_type: "GpArticle::Doc", category_id: 61, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 266, categorizable_id: 121, categorizable_type: "GpArticle::Doc", category_id: 75, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 195, categorizable_id: 87, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 201, categorizable_id: 90, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 271, categorizable_id: 124, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 202, categorizable_id: 90, categorizable_type: "GpArticle::Doc", category_id: 63, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 203, categorizable_id: 90, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 272, categorizable_id: 124, categorizable_type: "GpArticle::Doc", category_id: 76, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 204, categorizable_id: 91, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 205, categorizable_id: 91, categorizable_type: "GpArticle::Doc", category_id: 63, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 273, categorizable_id: 125, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 206, categorizable_id: 91, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 207, categorizable_id: 92, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 274, categorizable_id: 125, categorizable_type: "GpArticle::Doc", category_id: 76, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 208, categorizable_id: 92, categorizable_type: "GpArticle::Doc", category_id: 64, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 209, categorizable_id: 92, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 275, categorizable_id: 126, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 210, categorizable_id: 93, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 211, categorizable_id: 93, categorizable_type: "GpArticle::Doc", category_id: 64, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 276, categorizable_id: 126, categorizable_type: "GpArticle::Doc", category_id: 76, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 212, categorizable_id: 93, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 216, categorizable_id: 95, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 277, categorizable_id: 128, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 217, categorizable_id: 95, categorizable_type: "GpArticle::Doc", category_id: 65, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 218, categorizable_id: 96, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 278, categorizable_id: 128, categorizable_type: "GpArticle::Doc", category_id: 76, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 219, categorizable_id: 96, categorizable_type: "GpArticle::Doc", category_id: 65, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 222, categorizable_id: 98, categorizable_type: "GpArticle::Doc", category_id: 66, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 281, categorizable_id: 130, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 223, categorizable_id: 99, categorizable_type: "GpArticle::Doc", category_id: 66, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 226, categorizable_id: 101, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 282, categorizable_id: 130, categorizable_type: "GpArticle::Doc", category_id: 77, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 227, categorizable_id: 101, categorizable_type: "GpArticle::Doc", category_id: 67, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 228, categorizable_id: 101, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 284, categorizable_id: 132, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 229, categorizable_id: 102, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 230, categorizable_id: 102, categorizable_type: "GpArticle::Doc", category_id: 67, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 285, categorizable_id: 132, categorizable_type: "GpArticle::Doc", category_id: 77, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 231, categorizable_id: 102, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 234, categorizable_id: 104, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 287, categorizable_id: 133, categorizable_type: "GpArticle::Doc", category_id: 78, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 235, categorizable_id: 104, categorizable_type: "GpArticle::Doc", category_id: 68, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 237, categorizable_id: 106, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 288, categorizable_id: 133, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 238, categorizable_id: 106, categorizable_type: "GpArticle::Doc", category_id: 69, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 241, categorizable_id: 108, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 289, categorizable_id: 134, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 242, categorizable_id: 108, categorizable_type: "GpArticle::Doc", category_id: 69, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 249, categorizable_id: 112, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 290, categorizable_id: 134, categorizable_type: "GpArticle::Doc", category_id: 78, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 250, categorizable_id: 112, categorizable_type: "GpArticle::Doc", category_id: 71, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 251, categorizable_id: 113, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 291, categorizable_id: 135, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 252, categorizable_id: 113, categorizable_type: "GpArticle::Doc", category_id: 72, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 292, categorizable_id: 135, categorizable_type: "GpArticle::Doc", category_id: 78, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 261, categorizable_id: 119, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 293, categorizable_id: 136, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 262, categorizable_id: 119, categorizable_type: "GpArticle::Doc", category_id: 74, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 294, categorizable_id: 136, categorizable_type: "GpArticle::Doc", category_id: 79, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 303, categorizable_id: 141, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 297, categorizable_id: 138, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 298, categorizable_id: 138, categorizable_type: "GpArticle::Doc", category_id: 79, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 301, categorizable_id: 140, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 302, categorizable_id: 140, categorizable_type: "GpArticle::Doc", category_id: 80, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 304, categorizable_id: 141, categorizable_type: "GpArticle::Doc", category_id: 80, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 308, categorizable_id: 143, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 309, categorizable_id: 143, categorizable_type: "GpArticle::Doc", category_id: 80, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 310, categorizable_id: 144, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 311, categorizable_id: 144, categorizable_type: "GpArticle::Doc", category_id: 81, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 312, categorizable_id: 144, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 313, categorizable_id: 145, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 314, categorizable_id: 145, categorizable_type: "GpArticle::Doc", category_id: 81, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 317, categorizable_id: 148, categorizable_type: "GpArticle::Doc", category_id: 82, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 324, categorizable_id: 154, categorizable_type: "GpArticle::Doc", category_id: 85, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 450, categorizable_id: 262, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 146, categorizable_id: 70, categorizable_type: "GpArticle::Doc", category_id: 55, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 181, categorizable_id: 82, categorizable_type: "GpArticle::Doc", category_id: 19, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 147, categorizable_id: 70, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 267, categorizable_id: 122, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 148, categorizable_id: 71, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 185, categorizable_id: 84, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 149, categorizable_id: 71, categorizable_type: "GpArticle::Doc", category_id: 55, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 150, categorizable_id: 71, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 186, categorizable_id: 84, categorizable_type: "GpArticle::Doc", category_id: 60, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 151, categorizable_id: 72, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 268, categorizable_id: 122, categorizable_type: "GpArticle::Doc", category_id: 75, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 152, categorizable_id: 72, categorizable_type: "GpArticle::Doc", category_id: 56, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 187, categorizable_id: 84, categorizable_type: "GpArticle::Doc", category_id: 19, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 153, categorizable_id: 72, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 154, categorizable_id: 73, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 188, categorizable_id: 85, categorizable_type: "GpArticle::Doc", category_id: 61, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 155, categorizable_id: 73, categorizable_type: "GpArticle::Doc", category_id: 56, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 269, categorizable_id: 123, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 156, categorizable_id: 73, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 189, categorizable_id: 85, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 157, categorizable_id: 74, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 158, categorizable_id: 74, categorizable_type: "GpArticle::Doc", category_id: 56, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 190, categorizable_id: 86, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 159, categorizable_id: 74, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 270, categorizable_id: 123, categorizable_type: "GpArticle::Doc", category_id: 75, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 160, categorizable_id: 75, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 191, categorizable_id: 86, categorizable_type: "GpArticle::Doc", category_id: 61, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 161, categorizable_id: 75, categorizable_type: "GpArticle::Doc", category_id: 57, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 162, categorizable_id: 75, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 192, categorizable_id: 86, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 163, categorizable_id: 76, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 279, categorizable_id: 129, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 164, categorizable_id: 76, categorizable_type: "GpArticle::Doc", category_id: 58, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 196, categorizable_id: 88, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 165, categorizable_id: 76, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 166, categorizable_id: 77, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 197, categorizable_id: 88, categorizable_type: "GpArticle::Doc", category_id: 62, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 167, categorizable_id: 77, categorizable_type: "GpArticle::Doc", category_id: 58, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 280, categorizable_id: 129, categorizable_type: "GpArticle::Doc", category_id: 77, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 168, categorizable_id: 77, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 198, categorizable_id: 89, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 169, categorizable_id: 78, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 170, categorizable_id: 78, categorizable_type: "GpArticle::Doc", category_id: 58, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 199, categorizable_id: 89, categorizable_type: "GpArticle::Doc", category_id: 63, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 171, categorizable_id: 78, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 283, categorizable_id: 131, categorizable_type: "GpArticle::Doc", category_id: 77, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 172, categorizable_id: 79, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 200, categorizable_id: 89, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 173, categorizable_id: 79, categorizable_type: "GpArticle::Doc", category_id: 59, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 174, categorizable_id: 79, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 213, categorizable_id: 94, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 299, categorizable_id: 139, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 214, categorizable_id: 94, categorizable_type: "GpArticle::Doc", category_id: 64, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 300, categorizable_id: 139, categorizable_type: "GpArticle::Doc", category_id: 79, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 215, categorizable_id: 94, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 305, categorizable_id: 142, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 220, categorizable_id: 97, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 221, categorizable_id: 97, categorizable_type: "GpArticle::Doc", category_id: 65, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 306, categorizable_id: 142, categorizable_type: "GpArticle::Doc", category_id: 80, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 224, categorizable_id: 100, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 225, categorizable_id: 100, categorizable_type: "GpArticle::Doc", category_id: 66, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 307, categorizable_id: 142, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 232, categorizable_id: 103, categorizable_type: "GpArticle::Doc", category_id: 67, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 233, categorizable_id: 103, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 236, categorizable_id: 105, categorizable_type: "GpArticle::Doc", category_id: 68, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 239, categorizable_id: 107, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 240, categorizable_id: 107, categorizable_type: "GpArticle::Doc", category_id: 69, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 318, categorizable_id: 149, categorizable_type: "GpArticle::Doc", category_id: 83, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 243, categorizable_id: 109, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 244, categorizable_id: 109, categorizable_type: "GpArticle::Doc", category_id: 70, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 245, categorizable_id: 110, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 246, categorizable_id: 110, categorizable_type: "GpArticle::Doc", category_id: 71, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 247, categorizable_id: 111, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 320, categorizable_id: 151, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 248, categorizable_id: 111, categorizable_type: "GpArticle::Doc", category_id: 71, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 254, categorizable_id: 115, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 321, categorizable_id: 151, categorizable_type: "GpArticle::Doc", category_id: 83, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 255, categorizable_id: 115, categorizable_type: "GpArticle::Doc", category_id: 72, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 256, categorizable_id: 116, categorizable_type: "GpArticle::Doc", category_id: 73, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 322, categorizable_id: 152, categorizable_type: "GpArticle::Doc", category_id: 84, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 257, categorizable_id: 117, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 325, categorizable_id: 155, categorizable_type: "GpArticle::Doc", category_id: 86, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 258, categorizable_id: 117, categorizable_type: "GpArticle::Doc", category_id: 74, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 326, categorizable_id: 156, categorizable_type: "GpArticle::Doc", category_id: 86, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 259, categorizable_id: 118, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 260, categorizable_id: 118, categorizable_type: "GpArticle::Doc", category_id: 74, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 327, categorizable_id: 157, categorizable_type: "GpArticle::Doc", category_id: 86, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 359, categorizable_id: 180, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 330, categorizable_id: 159, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 331, categorizable_id: 159, categorizable_type: "GpArticle::Doc", category_id: 87, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 360, categorizable_id: 180, categorizable_type: "GpArticle::Doc", category_id: 101, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 332, categorizable_id: 160, categorizable_type: "GpArticle::Doc", category_id: 88, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 451, categorizable_id: 263, categorizable_type: "GpArticle::Doc", category_id: 46, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 333, categorizable_id: 161, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 363, categorizable_id: 182, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 334, categorizable_id: 161, categorizable_type: "GpArticle::Doc", category_id: 89, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 336, categorizable_id: 163, categorizable_type: "GpArticle::Doc", category_id: 91, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 364, categorizable_id: 182, categorizable_type: "GpArticle::Doc", category_id: 102, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 338, categorizable_id: 165, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 452, categorizable_id: 263, categorizable_type: "GpArticle::Doc", category_id: 13, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 339, categorizable_id: 165, categorizable_type: "GpArticle::Doc", category_id: 92, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 340, categorizable_id: 165, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 421, categorizable_id: 237, categorizable_type: "GpArticle::Doc", category_id: 133, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 342, categorizable_id: 167, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 343, categorizable_id: 167, categorizable_type: "GpArticle::Doc", category_id: 94, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 366, categorizable_id: 184, categorizable_type: "GpArticle::Doc", category_id: 103, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 344, categorizable_id: 168, categorizable_type: "GpArticle::Doc", category_id: 94, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 345, categorizable_id: 169, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 367, categorizable_id: 185, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 346, categorizable_id: 169, categorizable_type: "GpArticle::Doc", category_id: 95, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 368, categorizable_id: 185, categorizable_type: "GpArticle::Doc", category_id: 104, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 369, categorizable_id: 186, categorizable_type: "GpArticle::Doc", category_id: 105, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 485, categorizable_id: 280, categorizable_type: "GpArticle::Doc", category_id: 52, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 378, categorizable_id: 195, categorizable_type: "GpArticle::Doc", category_id: 107, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 380, categorizable_id: 197, categorizable_type: "GpArticle::Doc", category_id: 109, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 466, categorizable_id: 270, categorizable_type: "GpArticle::Doc", category_id: 16, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 381, categorizable_id: 198, categorizable_type: "GpArticle::Doc", category_id: 109, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 465, categorizable_id: 270, categorizable_type: "GpArticle::Doc", category_id: 46, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 384, categorizable_id: 201, categorizable_type: "GpArticle::Doc", category_id: 110, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 385, categorizable_id: 202, categorizable_type: "GpArticle::Doc", category_id: 110, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 471, categorizable_id: 273, categorizable_type: "GpArticle::Doc", category_id: 45, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 422, categorizable_id: 238, categorizable_type: "GpArticle::Doc", category_id: 133, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 472, categorizable_id: 273, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 392, categorizable_id: 208, categorizable_type: "GpArticle::Doc", category_id: 116, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 394, categorizable_id: 210, categorizable_type: "GpArticle::Doc", category_id: 115, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 398, categorizable_id: 214, categorizable_type: "GpArticle::Doc", category_id: 122, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 480, categorizable_id: 277, categorizable_type: "GpArticle::Doc", category_id: 60, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 408, categorizable_id: 224, categorizable_type: "GpArticle::Doc", category_id: 130, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 481, categorizable_id: 277, categorizable_type: "GpArticle::Doc", category_id: 19, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 424, categorizable_id: 240, categorizable_type: "GpArticle::Doc", category_id: 134, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 486, categorizable_id: 280, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 414, categorizable_id: 230, categorizable_type: "GpArticle::Doc", category_id: 131, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 428, categorizable_id: 243, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 417, categorizable_id: 233, categorizable_type: "GpArticle::Doc", category_id: 132, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 429, categorizable_id: 243, categorizable_type: "GpArticle::Doc", category_id: 136, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 430, categorizable_id: 244, categorizable_type: "GpArticle::Doc", category_id: 136, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 433, categorizable_id: 247, categorizable_type: "GpArticle::Doc", category_id: 137, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 436, categorizable_id: 250, categorizable_type: "GpArticle::Doc", category_id: 139, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 438, categorizable_id: 252, categorizable_type: "GpArticle::Doc", category_id: 140, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 443, categorizable_id: 257, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 444, categorizable_id: 258, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 445, categorizable_id: 258, categorizable_type: "GpArticle::Doc", category_id: 142, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 446, categorizable_id: 259, categorizable_type: "GpArticle::Doc", category_id: 143, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 447, categorizable_id: 260, categorizable_type: "GpArticle::Doc", category_id: 144, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 448, categorizable_id: 261, categorizable_type: "GpArticle::Doc", category_id: 43, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 523, categorizable_id: 294, categorizable_type: "GpArticle::Doc", category_id: 4, sort_no: nil, categorized_as: "GpCalendar::Event"},
  {id: 522, categorizable_id: 294, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 525, categorizable_id: 295, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 524, categorizable_id: 295, categorizable_type: "GpArticle::Doc", category_id: 125, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 534, categorizable_id: 298, categorizable_type: "GpArticle::Doc", category_id: 4, sort_no: nil, categorized_as: "GpCalendar::Event"},
  {id: 533, categorizable_id: 298, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 532, categorizable_id: 298, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 328, categorizable_id: 158, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 361, categorizable_id: 181, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 329, categorizable_id: 158, categorizable_type: "GpArticle::Doc", category_id: 87, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 335, categorizable_id: 162, categorizable_type: "GpArticle::Doc", category_id: 90, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 362, categorizable_id: 181, categorizable_type: "GpArticle::Doc", category_id: 102, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 337, categorizable_id: 164, categorizable_type: "GpArticle::Doc", category_id: 92, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 453, categorizable_id: 264, categorizable_type: "GpArticle::Doc", category_id: 57, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 370, categorizable_id: 187, categorizable_type: "GpArticle::Doc", category_id: 105, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 371, categorizable_id: 188, categorizable_type: "GpArticle::Doc", category_id: 106, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 347, categorizable_id: 170, categorizable_type: "GpArticle::Doc", category_id: 95, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 454, categorizable_id: 264, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 419, categorizable_id: 235, categorizable_type: "GpArticle::Doc", category_id: 132, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 373, categorizable_id: 190, categorizable_type: "GpArticle::Doc", category_id: 108, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 349, categorizable_id: 172, categorizable_type: "GpArticle::Doc", category_id: 96, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 455, categorizable_id: 265, categorizable_type: "GpArticle::Doc", category_id: 82, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 350, categorizable_id: 173, categorizable_type: "GpArticle::Doc", category_id: 97, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 374, categorizable_id: 191, categorizable_type: "GpArticle::Doc", category_id: 108, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 351, categorizable_id: 174, categorizable_type: "GpArticle::Doc", category_id: 97, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 352, categorizable_id: 175, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 456, categorizable_id: 265, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 353, categorizable_id: 175, categorizable_type: "GpArticle::Doc", category_id: 98, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 354, categorizable_id: 176, categorizable_type: "GpArticle::Doc", category_id: 11, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 355, categorizable_id: 176, categorizable_type: "GpArticle::Doc", category_id: 98, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 356, categorizable_id: 177, categorizable_type: "GpArticle::Doc", category_id: 99, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 423, categorizable_id: 239, categorizable_type: "GpArticle::Doc", category_id: 134, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 382, categorizable_id: 199, categorizable_type: "GpArticle::Doc", category_id: 110, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 386, categorizable_id: 203, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 464, categorizable_id: 269, categorizable_type: "GpArticle::Doc", category_id: 20, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 387, categorizable_id: 203, categorizable_type: "GpArticle::Doc", category_id: 114, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 463, categorizable_id: 269, categorizable_type: "GpArticle::Doc", category_id: 53, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 389, categorizable_id: 205, categorizable_type: "GpArticle::Doc", category_id: 112, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 390, categorizable_id: 206, categorizable_type: "GpArticle::Doc", category_id: 112, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 467, categorizable_id: 271, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 468, categorizable_id: 271, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 393, categorizable_id: 209, categorizable_type: "GpArticle::Doc", category_id: 117, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 395, categorizable_id: 211, categorizable_type: "GpArticle::Doc", category_id: 121, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 469, categorizable_id: 272, categorizable_type: "GpArticle::Doc", category_id: 44, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 396, categorizable_id: 212, categorizable_type: "GpArticle::Doc", category_id: 119, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 397, categorizable_id: 213, categorizable_type: "GpArticle::Doc", category_id: 120, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 470, categorizable_id: 272, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 399, categorizable_id: 215, categorizable_type: "GpArticle::Doc", category_id: 123, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 401, categorizable_id: 217, categorizable_type: "GpArticle::Doc", category_id: 124, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 402, categorizable_id: 218, categorizable_type: "GpArticle::Doc", category_id: 125, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 404, categorizable_id: 220, categorizable_type: "GpArticle::Doc", category_id: 126, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 405, categorizable_id: 221, categorizable_type: "GpArticle::Doc", category_id: 127, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 406, categorizable_id: 222, categorizable_type: "GpArticle::Doc", category_id: 128, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 477, categorizable_id: 275, categorizable_type: "GpArticle::Doc", category_id: 18, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 407, categorizable_id: 223, categorizable_type: "GpArticle::Doc", category_id: 129, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 409, categorizable_id: 225, categorizable_type: "GpArticle::Doc", category_id: 131, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 478, categorizable_id: 276, categorizable_type: "GpArticle::Doc", category_id: 46, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 425, categorizable_id: 241, categorizable_type: "GpArticle::Doc", category_id: 135, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 479, categorizable_id: 276, categorizable_type: "GpArticle::Doc", category_id: 21, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 482, categorizable_id: 278, categorizable_type: "GpArticle::Doc", category_id: 88, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 416, categorizable_id: 232, categorizable_type: "GpArticle::Doc", category_id: 132, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 483, categorizable_id: 278, categorizable_type: "GpArticle::Doc", category_id: 17, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 484, categorizable_id: 279, categorizable_type: "GpArticle::Doc", category_id: 97, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 426, categorizable_id: 242, categorizable_type: "GpArticle::Doc", category_id: 9, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 427, categorizable_id: 242, categorizable_type: "GpArticle::Doc", category_id: 136, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 431, categorizable_id: 245, categorizable_type: "GpArticle::Doc", category_id: 137, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 432, categorizable_id: 246, categorizable_type: "GpArticle::Doc", category_id: 137, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 434, categorizable_id: 248, categorizable_type: "GpArticle::Doc", category_id: 138, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 435, categorizable_id: 249, categorizable_type: "GpArticle::Doc", category_id: 138, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 439, categorizable_id: 253, categorizable_type: "GpArticle::Doc", category_id: 140, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 440, categorizable_id: 254, categorizable_type: "GpArticle::Doc", category_id: 141, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 441, categorizable_id: 255, categorizable_type: "GpArticle::Doc", category_id: 141, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 492, categorizable_id: 282, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 493, categorizable_id: 282, categorizable_type: "GpArticle::Doc", category_id: 118, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 494, categorizable_id: 282, categorizable_type: "GpArticle::Doc", category_id: 133, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 503, categorizable_id: 287, categorizable_type: "GpArticle::Doc", category_id: 14, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 502, categorizable_id: 287, categorizable_type: "GpArticle::Doc", category_id: 1, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 501, categorizable_id: 287, categorizable_type: "GpArticle::Doc", category_id: 63, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 512, categorizable_id: 290, categorizable_type: "GpArticle::Doc", category_id: 12, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 511, categorizable_id: 290, categorizable_type: "GpArticle::Doc", category_id: 114, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 510, categorizable_id: 290, categorizable_type: "GpArticle::Doc", category_id: 79, sort_no: nil, categorized_as: "GpArticle::Doc"},
  {id: 521, categorizable_id: 294, categorizable_type: "GpArticle::Doc", category_id: 121, sort_no: nil, categorized_as: "GpArticle::Doc"}
])
GpCategory::CategoryType.create!([
  {id: 2, content_id: 2, concept_id: 1, layout_id: nil, state: "public", name: "kubun", title: "区分", sort_no: 10, sitemap_state: "visible", docs_order: "display_updated_at DESC, updated_at DESC", template_id: nil, internal_category_type_id: nil, description: ""},
  {id: 1, content_id: 2, concept_id: 1, layout_id: nil, state: "public", name: "bunya", title: "分野", sort_no: 20, sitemap_state: "visible", docs_order: "", template_id: nil, internal_category_type_id: nil, description: ""},
  {id: 3, content_id: 2, concept_id: 1, layout_id: nil, state: "public", name: "lifeevent", title: "ライフイベント", sort_no: 30, sitemap_state: "visible", docs_order: "display_updated_at DESC, updated_at DESC", template_id: nil, internal_category_type_id: nil, description: ""},
  {id: 4, content_id: 2, concept_id: 1, layout_id: nil, state: "public", name: "event", title: "イベント情報", sort_no: 40, sitemap_state: "visible", docs_order: "display_updated_at DESC, updated_at DESC", template_id: nil, internal_category_type_id: nil, description: ""}
])
GpCategory::TemplateModule.create!([
  {id: 5, content_id: 2, name: "docs_1", title: "記事一覧：自カテゴリ以下全て", module_type: "docs_1", module_type_feature: "---\n- 1\n", wrapper_tag: "li", doc_style: "@title_link@（@update_date@ @group@）", num_docs: 1, upper_text: "<div class=\"articleHeader\"><h2>新着情報</h2></div>\r\n<ul class=\"feed\">\r\n  <li><a class=\"feedRss\" title=\"RSSフィードを取得\" href=\"index.rss\">RSS</a></li>\r\n  <li><a class=\"feedAtom\" title=\"Atomフィードを取得\" href=\"index.atom\">Atom</a></li>\r\n</ul>", lower_text: ""},
  {id: 6, content_id: 2, name: "docs_2", title: "記事一覧：自カテゴリのみ", module_type: "docs_2", module_type_feature: "---\n- 11\n", wrapper_tag: "li", doc_style: "@title_link@", num_docs: 100, upper_text: "", lower_text: ""},
  {id: 4, content_id: 2, name: "docs_7", title: "記事一覧：自カテゴリ直下のカテゴリ（カテゴリで分類）", module_type: "docs_7", module_type_feature: "---\n- 11\n", wrapper_tag: "li", doc_style: "@title_link@", num_docs: 10, upper_text: "", lower_text: ""},
  {id: 7, content_id: 2, name: "docs_2-lifeevent", title: "記事一覧：自カテゴリ以下全て（ライフイベント）", module_type: "docs_1", module_type_feature: "--- []\n", wrapper_tag: "li", doc_style: "@title_link@", num_docs: 100, upper_text: "", lower_text: ""}
])
GpCategory::Template.create!([
  {id: 5, content_id: 2, name: "kubun", title: "区分", body: "[[module/docs_1]]"},
  {id: 6, content_id: 2, name: "event", title: "イベント情報", body: "[[module/docs_1]]"},
  {id: 7, content_id: 2, name: "bunya-2", title: "分野第二回層", body: "[[module/docs_1]]\r\n[[module/docs_2]]"},
  {id: 3, content_id: 2, name: "bunya-1", title: "分野第一階層", body: "[[module/docs_1]]\r\n[[module/docs_7]]"},
  {id: 4, content_id: 2, name: "lifeevent", title: "ライフイベント", body: "[[module/docs_2-lifeevent]]"}
])
